name: "Pull Request Check CI"

on:
  pull_request:

jobs:
  build:
    name: NodeJS CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "true"
          token: ${{ secrets.GHB_USER_TOKEN }}

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

      - name: Lint files
        run: yarn lint

      - name: build, test and generate coverage report
        run: |
          yarn build
          yarn build:docs

      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: "C01BL91B7TQ" #Channel ID
          username: "YV Github Action"
          author_name: "CI Details"
          # if_mention: "failure,cancelled"
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          GITHUB_TOKEN: ${{ github.token }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
        if: always() # Pick up events even if the job fails or is canceled.
